### ISSUE TITLE
CLI Install

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#126]
I preface this by saying I haven't done much with linux in years, so it's entirely possible I screwed up something. That said, I had to run the CLI installation with sudo to get it to work. I.e.

sudo npm install --global tallyarbiter

The CLI install doc doesn't mention running as root, so I'm not sure if I did something wrong with the npm install or it's just assumed that everyone would know this.

**Comment by hrueger** [comment]
I believe that the error is because the directory for installing packages with npm globally is not writable for your user. That depends on your linux distro. And on windows you don't have a sudo, it just works there.
But you're right, we should add a `You may need to run the command as root using the prefix "sudo".`

**Comment by josephdadams** [comment]
Added this to the docs
