### ISSUE TITLE
Analog Way Livecore unable to connect.

### ISSUE THREAD

**Issue by jordannwj** [josephdadams/TallyArbiter#150]
Unable to key in IP address and port number for analog way live core.

### Version

2.0.8

### What browsers are you seeing the problem on?

Safari

**Comment by josephdadams** [comment]
I confirmed this, on my version 2.0.8, when I click that source type, it actually was showing the "internal webhook" source type fields instead of the analog way fields.

**Comment by JTF4** [comment]
Interesting. Did the ID of that source type somehow get reset to the webhook one?

**Comment by josephdadams** [comment]
It doesn’t appear that way in the master branch.

**Comment by josephdadams** [comment]
@hrueger could it be a UI bug pulling the wrong source type?

**Comment by hrueger** [comment]
I can confirm that bug, still investigating

**Comment by hrueger** [comment]
So the problem is the following: In the UI we get the index of the selected source type. This index is from the filtered list. Then, when displaying the fields, we get the options using the index of the unfiltered array. The `incoming webhook` source is disabled, which means that it is missing in the filtered list. This causes the index for the unfiltered list to be off by +1.
I suggest that we filter in the `socket.service.ts` as we don't need the disabled source types anywhere in the UI.

Unfortunately, I probably don't have time to do that today. Maybe someone else could implement this fix?

**Comment by MatteoGheza** [comment]
> Unfortunately, I probably don't have time to do that today. Maybe someone else could implement this fix?

Ok, I'm working on It.

**Comment by MatteoGheza** [comment]
Now I'm releasing a new version with this fix.

**Comment by MatteoGheza** [comment]
@jordannwj @JTF4 @josephdadams fixed in 2.0.9
