### ISSUE TITLE
QR code generator for external address

### ISSUE THREAD

**Issue by videojedi** [josephdadams/TallyArbiter#175]
Could the QR code generator offer an external address option for cloud/port forward situations?

RB

**Comment by JTF4** [comment]
Are you talking about an option to make a QR code with an option for a different port other than 4455?

**Comment by josephdadams** [comment]
I think the issue is that the server has to be aware of the port forward for it to be generated automatically. The easiest thing here would be to add a text field for url with persistent data storage that would allow the user to generate a custom QR code. I do think anyone scanning the QR code isn’t likely going to be or shouldn’t be on the same production network. So it’s likely going to be a port forward or cloud situation.

**Comment by videojedi** [comment]
A manual text box (or even an entry in conf file) would be fine.

**Comment by MatteoGheza** [comment]
Done
