### ISSUE TITLE
Send osc to Companion 2.0 no response.....

### ISSUE THREAD

**Issue by houtacheng** [josephdadams/TallyArbiter#2]
I really like this program.
I'm trying to send an osc message to companion when the Device Program On Actions.
like this:
http://10.31.12.186:12321/press/bank/1/2
But there's no response. What can I do about it?
![image](https://user-images.githubusercontent.com/25832189/87203310-b3978e80-c2d8-11ea-8938-a8def464236a.png)

**Comment by josephdadams** [comment]
Let me see if I can recreate the issue. Are you getting any error messages in the Tally Arbiter terminal window?

**Comment by houtacheng** [comment]
![image](https://user-images.githubusercontent.com/25832189/87187777-19c5e680-c2c4-11ea-9b43-ce1df2fc1abe.png)

**Comment by houtacheng** [comment]
![image](https://user-images.githubusercontent.com/25832189/87203225-82b75980-c2d8-11ea-88c0-69f56d61298b.png)

**Comment by houtacheng** [comment]
but If i used 10.31.12.186, no any error messages.

**Comment by houtacheng** [comment]
If i used Outgoing Webhook:
![image](https://user-images.githubusercontent.com/25832189/87204052-45ec6200-c2da-11ea-9fec-87ff2c3c1a85.png)

**Comment by josephdadams** [comment]
I have the OSC issue fixed, Companion expects zero arguments to trigger a button and TA was sending an unnecessary argument. This will be fixed in the next release of Tally Arbiter. As for your other issue with the outgoing webhook, I have made a logic change to check if the path starts with a "/" and adds it if present. It was previously assuming that the slash would not be entered by the user. Until the next version is released, just remove the beginning `/` from your webhook path and it should not return a 404 error.
