### ISSUE TITLE
[Feature Request]: Add Error Reports to Menu / Home Screen / any other screen

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#200]
### What feature would you like to see added to TallyArbiter?

I just got an Error Report but clicked away the dialog by accident. How can I get to the `error-list` component? Is it somewhere in the UI and I just cannot find it?

**Comment by MatteoGheza** [comment]
![chrome_gnEJcLWwVK](https://user-images.githubusercontent.com/27729549/131726884-5b7b93e8-12fd-46bc-8c75-76fe70a8ed18.png)
You need to go to "`/#/errors`". I don't think it's necesary to add a link to the error reports list, since if you have any unreaded error report a dialog is shown every time you open settings page.
If you want, I'll add a link to the error reports list in footer, near version.

**Comment by hrueger** [comment]
Ah, I didn't go to the settings page. Yes, I can confirm that this is working.

>If you want, I'll add a link to the error reports list in footer, near version.
Yeah, why not? Sounds like a good idea.
