### ISSUE TITLE
[Feature Request]: make security logins editable through Ui

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#210]
### What feature would you like to see added to TallyArbiter?

Let the user modify the settings and producer pages logins through the UI. Including removing completely if that’s what they really want.

**Comment by hrueger** [comment]
Great idea, I like it. It would also be nice to be able to add multiple users with different credentials.

However, please let's either do this directly in #204 or in a feature branch after #204 is merged because we already have a huge merge conflict there. That will be even bigger with more changes to master.
