### ISSUE TITLE
M5Sticks creating new listeners for same IP

### ISSUE THREAD

**Issue by KenBJohnson** [josephdadams/TallyArbiter#32]
I apologize if this is something I'm missing in the docs so please just close if so with my apologies as I'm new to the etiquette of github projects but it our M5stick-Cs have static IPs and reconnect at the same IP every time to TallyArbiter but they seem to create new listeners on occasion (maybe after coming out of sleep/turned off).

This means that they default to our Camera 1 again and we have to reconfigure them to the right devices.

The net effect is we end up with multiple M5 sticks as listeners with the same IPs in the admin interface, the old ones grayed out. I tried to determine if we could add permanent configs for listeners in the config.json but missed it if so.  Thank you!

**Comment by josephdadams** [comment]
If you’re seeing one greyed out, it’s because it lost connection. Then it reconnects. All the other listener clients remember their last state and reconnect with that device id. This one does not in the currently available version. I will remedy that in the next release of the m5 client. For now, a solution would be to modify the code before to upload it to the stick and hardcode a device id.

**Comment by KenBJohnson** [comment]
Ok thank you - that makes sense. I'll try tweaking the stick code until
then - we sure appreciate all the work and expertise that has gone into
this project!
