### ISSUE TITLE
Add Reconnect button to source list in GUI for any source that is disconnected

### ISSUE THREAD

**Issue by hadphild** [josephdadams/TallyArbiter#33]
If you open TallyArbiter before Vmix on the same system it does not connect. A reconnect button would be really useful on the main interface.

**Comment by josephdadams** [comment]
Great idea! Maybe a reconnect button appears next to any source that is disconnected? (As a workaround for now you can edit the source, change nothing and hit save and it will reinitiate.) It’s mostly due to the client/server relationship and I don’t want to endlessly ping a server that’s not there.

**Comment by josephdadams** [comment]
This is implemented in the latest commit.
