### ISSUE TITLE
OBS - system confused by fade-to-black

### ISSUE THREAD

**Issue by smadds** [josephdadams/TallyArbiter#44]
FTB would normally turn off all tallies, but when connected to OBS (v26.1.1) in Studio mode, the system indicates the PV source as on air when faded to black. Coming out of FTB goes back to the original PGM source, but the tallies still show the PV channel as on-air

**Comment by josephdadams** [comment]
Verified. I will see what I can do to resolve this, but it looks like it's actually emitting an event with that PV source in PGM, hence Tally Arbiter is acting on it. A workaround in the meantime is to make a simple "Black" scene and just switch to that scene when needed.

**Comment by josephdadams** [comment]
A "fade to black" also issues a transition to the currently selected preview scene when in Studio Mode. So this is going to be problematic to fix.

TA would have to track all scenes and what sources are currently active in each scene, because when you issue a "fade to black" transition, it simultaneously issues a `SwitchScenes` event (which affects what goes into PGM based on the Sources listed in that `SwitchScenes` event) along with `TransitionBegin` and `TransitionEnd` events. Those two latter events contain a "toScene" (which is '', i.e. black) and the `transitionBegin` also contains the `fromScene`. They don't contain any Source data.

So, all that said, this would require a big reworking of the OBS functions, and not a high priority for what I assume is not a huge use case. I suggest for now using the workaround I proposed of using a Scene with no Sources, which will issue the fade to black as desired and take the sources out of tally.

If someone wants to propose the code to fix this, I would review it and accept the PR.
