### ISSUE TITLE
[Bug]: Tricaster not working with >3.0

### ISSUE THREAD

**Issue by lehart1j** [josephdadams/TallyArbiter#541]
### What happened?

When using a Tricaster it does not appear to change tally when using any version post 3.0

### Version

3.0.2

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by kolele** [comment]
I confirm that no Tricaster Tally data is coming to TA at all.

Is there any information that i can provide which would help troubleshoot this?

**Comment by kolele** [comment]
@josephdadams thank you for quick response!

With v2.0.16 data is indeed reaching TA, but the issue is that 2.0.16 has no mechanism for automatic reconnect.

Not having automatic reconnect after device is offline for lets say 2 hours will require someone to manually click reconnect button which in our case is not good enough.

Are there plans to take a look at V3 and maybe fix this issue or add automatic reconnect to V2?

Best regards.

**Comment by josephdadams** [comment]
I created Tally Arbiter for free and let the community contribute, but I am no longer at a point where I can work on it for free. Any coding time I have available, I need to do it to help support my family. If that's something you want to discuss, I am happy to have that conversation privately, but otherwise, I personally won't be putting any time into it.

**Comment by kolele** [comment]
@josephdadams i have sent you an email.

**Comment by Jocke4f** [comment]
We have added both improvements in connect and reconnect handling also for Tricaster. These improvements are included in 3.0.5 but I don't have a Tricaster available so I can't verify it. Does it work now on 3.0.5?

**Comment by kolele** [comment]
Hello,

Do you plan on releasing some binaries of 3.0.5?

Having trouble compiling from source by instructions posted on home page.

Would gladly test afterwards.

**Comment by kolele** [comment]
Just tried v3.0.6. Sadly no tally data is coming to TA from Tricaster at all...

**Comment by lehart1j** [comment]
> Just tried v3.0.6. Sadly no tally data is coming to TA from Tricaster at all...

I too can confirm this, just tired now and it isn't sending any tally data. I thought I was going insane, I know it's been awhile since I used TA but I knew I was setting it up correctly!

**Comment by kolele** [comment]
Are there any plans for fixing this?

**Comment by Jocke4f** [comment]
I will make an attempt on fixing this.
