### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by commputethis** [josephdadams/TallyArbiter#588]
How likely will it be that any additional releases will be made for this?  It's been close to 2 years since there was a production release.  There have been some beta/pre-release versions, but there haven't even been any of those in over a year.

**Comment by josephdadams** [comment]
It's an open source project so anyone can contribute at any time.

I started it in 2020 to meet the needs of my church. It does that perfectly. I then added a lot of features to help the community.

I'm at a point now where any available coding time, I need to use it to support my family. So if there's something you need and you're interested in hiring me to write that for you, feel free to reach out.

Otherwise, I'll continue monitoring the repo for submissions from the community.
